'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ChiriNulluo.Mahjong.Precure.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Faul に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property LabelNoYakus() As String
            Get
                Return ResourceManager.GetString("LabelNoYakus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0000() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0000", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0101() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0101", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0102() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0102", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0103() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0103", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0200() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0200", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0201() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0201", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0202() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0202", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0203() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0203", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0300() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0300", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0301() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0301", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0302() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0302", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0303() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0303", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0304() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0304", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0305() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0305", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0306() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0306", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0400() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0400", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0401() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0401", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0402() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0402", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0403() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0403", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0404() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0404", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0500() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0500", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0501() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0501", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0502() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0502", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0503() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0503", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0504() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0504", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0600() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0600", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0601() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0601", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0602() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0602", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0603() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0603", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0604() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0604", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0605() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0605", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0700() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0700", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0701() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0701", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0702() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0702", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0703() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0703", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0704() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0704", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0705() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0705", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0706() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0706", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0800() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0800", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0801() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0801", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0802() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0802", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0803() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0803", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0804() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0804", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0805() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0805", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0900() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0900", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0901() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0901", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0902() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0902", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0903() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0903", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure0904() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure0904", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure1001() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure1001", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure1002() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure1002", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure1003() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure1003", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure1004() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure1004", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure1101() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure1101", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure1102() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure1102", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure1103() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure1103", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure1201() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure1201", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure1202() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure1202", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure1203() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure1203", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure1204() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure1204", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure1205() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure1205", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure1206() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure1206", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure1301() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure1301", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure1302() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure1302", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Precure1303() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precure1303", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0000() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0000", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0101() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0101", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0102() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0102", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0103() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0103", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0200() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0200", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0201() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0201", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0202() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0202", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0203() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0203", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0300() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0300", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0301() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0301", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0302() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0302", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0303() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0303", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0304() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0304", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0305() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0305", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0306() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0306", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0400() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0400", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0401() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0401", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0402() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0402", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0403() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0403", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0404() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0404", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0500() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0500", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0501() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0501", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0502() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0502", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0503() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0503", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0504() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0504", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0600() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0600", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0601() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0601", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0602() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0602", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0603() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0603", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0604() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0604", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0605() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0605", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0700() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0700", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0701() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0701", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0702() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0702", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0703() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0703", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0704() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0704", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0705() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0705", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0706() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0706", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0800() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0800", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0801() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0801", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0802() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0802", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0803() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0803", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0804() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0804", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0805() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0805", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0900() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0900", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0901() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0901", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0902() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0902", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0903() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0903", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged0904() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged0904", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged1001() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged1001", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged1002() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged1002", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged1003() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged1003", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged1004() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged1004", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged1101() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged1101", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged1102() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged1102", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged1103() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged1103", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged1201() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged1201", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged1202() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged1202", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged1203() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged1203", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged1204() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged1204", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged1205() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged1205", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged1206() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged1206", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged1301() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged1301", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged1302() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged1302", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileEnlarged1303() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileEnlarged1303", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
