'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ChiriNulluo.Mahjong.WinFormApplication.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Button0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Button1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Button2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Draw... I&apos;ll win next. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CharacterScriptEasDraw() As String
            Get
                Return ResourceManager.GetString("CharacterScriptEasDraw", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ... に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CharacterScriptEasGameStart() As String
            Get
                Return ResourceManager.GetString("CharacterScriptEasGameStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Oh, damn...You won. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CharacterScriptEasLose() As String
            Get
                Return ResourceManager.GetString("CharacterScriptEasLose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Oh dear. It was boring time. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CharacterScriptEasWinDraw() As String
            Get
                Return ResourceManager.GetString("CharacterScriptEasWinDraw", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ron !! に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CharacterScriptEasWinRon() As String
            Get
                Return ResourceManager.GetString("CharacterScriptEasWinRon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''   に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CharacterScriptKotohaDraw() As String
            Get
                Return ResourceManager.GetString("CharacterScriptKotohaDraw", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''   に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CharacterScriptKotohaGameStart() As String
            Get
                Return ResourceManager.GetString("CharacterScriptKotohaGameStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''   に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CharacterScriptKotohaLose() As String
            Get
                Return ResourceManager.GetString("CharacterScriptKotohaLose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''   に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CharacterScriptKotohaWinDraw() As String
            Get
                Return ResourceManager.GetString("CharacterScriptKotohaWinDraw", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''   に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CharacterScriptKotohaWinRon() As String
            Get
                Return ResourceManager.GetString("CharacterScriptKotohaWinRon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''   に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CharacterScriptMiraiDraw() As String
            Get
                Return ResourceManager.GetString("CharacterScriptMiraiDraw", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''   に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CharacterScriptMiraiGameStart() As String
            Get
                Return ResourceManager.GetString("CharacterScriptMiraiGameStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''   に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CharacterScriptMiraiLose() As String
            Get
                Return ResourceManager.GetString("CharacterScriptMiraiLose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''   に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CharacterScriptMiraiWinDraw() As String
            Get
                Return ResourceManager.GetString("CharacterScriptMiraiWinDraw", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''   に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CharacterScriptMiraiWinRon() As String
            Get
                Return ResourceManager.GetString("CharacterScriptMiraiWinRon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Next time ! に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CharacterScriptReginaDraw() As String
            Get
                Return ResourceManager.GetString("CharacterScriptReginaDraw", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Do you think you could beat me?? に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CharacterScriptReginaGameStart() As String
            Get
                Return ResourceManager.GetString("CharacterScriptReginaGameStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  No way! Mana is much stronger than you ! に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CharacterScriptReginaLose() As String
            Get
                Return ResourceManager.GetString("CharacterScriptReginaLose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  YEAH！ I won ! に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CharacterScriptReginaWinDraw() As String
            Get
                Return ResourceManager.GetString("CharacterScriptReginaWinDraw", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  YEAH！ I won ! に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CharacterScriptReginaWinRon() As String
            Get
                Return ResourceManager.GetString("CharacterScriptReginaWinRon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''   に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CharacterScriptRikoDraw() As String
            Get
                Return ResourceManager.GetString("CharacterScriptRikoDraw", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''   に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CharacterScriptRikoGameStart() As String
            Get
                Return ResourceManager.GetString("CharacterScriptRikoGameStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''   に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CharacterScriptRikoLose() As String
            Get
                Return ResourceManager.GetString("CharacterScriptRikoLose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''   に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CharacterScriptRikoWinDraw() As String
            Get
                Return ResourceManager.GetString("CharacterScriptRikoWinDraw", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''   に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CharacterScriptRikoWinRon() As String
            Get
                Return ResourceManager.GetString("CharacterScriptRikoWinRon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Face_Eas01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Face_Eas01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Face_Eas02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Face_Eas02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Face_Eas03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Face_Eas03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Face_Kotoha01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Face_Kotoha01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Face_Kotoha02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Face_Kotoha02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Face_Kotoha03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Face_Kotoha03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Face_Mirai01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Face_Mirai01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Face_Mirai02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Face_Mirai02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Face_Mirai03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Face_Mirai03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Face_Regina01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Face_Regina01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Face_Regina02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Face_Regina02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Face_Regina03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Face_Regina03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Face_Riko01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Face_Riko01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Face_Riko02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Face_Riko02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Face_Riko03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Face_Riko03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property FallenTileBase() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FallenTileBase", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Frame0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frame0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property GameStartButton0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GameStartButton0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property GameStartButton1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GameStartButton1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property GameStartButton2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GameStartButton2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  COM に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDPlayerCOM() As String
            Get
                Return ResourceManager.GetString("IDPlayerCOM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Human に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDPlayerHuman() As String
            Get
                Return ResourceManager.GetString("IDPlayerHuman", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ChoiceForSkill に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDProcessChoiceForSkill() As String
            Get
                Return ResourceManager.GetString("IDProcessChoiceForSkill", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Chow に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDProcessChow() As String
            Get
                Return ResourceManager.GetString("IDProcessChow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  DiscardTile に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDProcessDiscardTile() As String
            Get
                Return ResourceManager.GetString("IDProcessDiscardTile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Haipai-P0 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDProcessHaipai_P0() As String
            Get
                Return ResourceManager.GetString("IDProcessHaipai_P0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Haipai-P1 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDProcessHaipai_P1() As String
            Get
                Return ResourceManager.GetString("IDProcessHaipai_P1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Haipai-Wall に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDProcessHaipai_Wall() As String
            Get
                Return ResourceManager.GetString("IDProcessHaipai_Wall", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  MeesageWindowChoice に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDProcessMeesageWindowChoice() As String
            Get
                Return ResourceManager.GetString("IDProcessMeesageWindowChoice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  NextRoundButton に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDProcessNextRoundButton() As String
            Get
                Return ResourceManager.GetString("IDProcessNextRoundButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Riichi に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDProcessRiichi() As String
            Get
                Return ResourceManager.GetString("IDProcessRiichi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  SelectOpponent に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDProcessSelectOpponent() As String
            Get
                Return ResourceManager.GetString("IDProcessSelectOpponent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  RD に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDProcessTypeRD() As String
            Get
                Return ResourceManager.GetString("IDProcessTypeRD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  UA に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDProcessTypeUA() As String
            Get
                Return ResourceManager.GetString("IDProcessTypeUA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  UN に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDProcessTypeUN() As String
            Get
                Return ResourceManager.GetString("IDProcessTypeUN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  UseSkill に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDProcessUseSkill() As String
            Get
                Return ResourceManager.GetString("IDProcessUseSkill", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property InitialForm_Back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InitialForm_Back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Chow に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property LabelChow() As String
            Get
                Return ResourceManager.GetString("LabelChow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  CureJong に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property LabelGameTitle() As String
            Get
                Return ResourceManager.GetString("LabelGameTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  No に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property LabelNo() As String
            Get
                Return ResourceManager.GetString("LabelNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  No Yakus に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property LabelNoYakus() As String
            Get
                Return ResourceManager.GetString("LabelNoYakus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  OK に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property LabelOK() As String
            Get
                Return ResourceManager.GetString("LabelOK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Pass に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property LabelPass() As String
            Get
                Return ResourceManager.GetString("LabelPass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Point に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property LabelPoint() As String
            Get
                Return ResourceManager.GetString("LabelPoint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Pong に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property LabelPong() As String
            Get
                Return ResourceManager.GetString("LabelPong", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ron に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property LabelRon() As String
            Get
                Return ResourceManager.GetString("LabelRon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Yaku Condition に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property LabelYakuCondition() As String
            Get
                Return ResourceManager.GetString("LabelYakuCondition", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Yes に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property LabelYes() As String
            Get
                Return ResourceManager.GetString("LabelYes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  You に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property LabelYou() As String
            Get
                Return ResourceManager.GetString("LabelYou", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Riichi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Riichi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property RiichiButton0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RiichiButton0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property RiichiButton1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RiichiButton1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property RiichiButton2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RiichiButton2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property RuleButton0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RuleButton0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property RuleButton1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RuleButton1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property RuleButton2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RuleButton2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property StoodTileBase() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StoodTileBase", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  You cannot declare Ron or Tsumo unless some yaku other than bonus tile is accomplished.Penalty minus 3000 points mofu. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SystemScriptChomboWarning() As String
            Get
                Return ResourceManager.GetString("SystemScriptChomboWarning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Do you really concede ? に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SystemScriptConfirmConcede() As String
            Get
                Return ResourceManager.GetString("SystemScriptConfirmConcede", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Will you finish with this hand ? に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SystemScriptConfirmFinish() As String
            Get
                Return ResourceManager.GetString("SystemScriptConfirmFinish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Will you pong ? に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SystemScriptConfirmPong() As String
            Get
                Return ResourceManager.GetString("SystemScriptConfirmPong", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Will you ron ? に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SystemScriptConfirmRon() As String
            Get
                Return ResourceManager.GetString("SystemScriptConfirmRon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Drawn game. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SystemScriptDrawnGame() As String
            Get
                Return ResourceManager.GetString("SystemScriptDrawnGame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Are you sure you want to exit ? に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SystemScriptExitConfirmation() As String
            Get
                Return ResourceManager.GetString("SystemScriptExitConfirmation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property SystemWindow02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SystemWindow02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property TileStoodBack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileStoodBack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Next Draw に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TileToNextDraw() As String
            Get
                Return ResourceManager.GetString("TileToNextDraw", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
